import React from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Container,
  Typography,
  Button,
  Card,
  CardContent,
  Paper,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Divider,
} from '@mui/material';
import Grid from '@mui/material/Grid'; 
import {
  School,
  Assessment,
  TrendingUp,
  Security,
  AccessTime,
  EmojiEvents,
  CheckCircle,
  ArrowForward,
  PlayCircle,
} from '@mui/icons-material';

const LandingPage: React.FC = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: <Assessment />,
      title: 'AI-Powered Assessments',
      description: 'Get personalized questions generated by advanced AI models',
    },
    {
      icon: <TrendingUp />,
      title: 'Real-time Feedback',
      description: 'Instant scoring and detailed performance analysis',
    },
    {
      icon: <Security />,
      title: 'Integrity Monitoring',
      description: 'Advanced proctoring to ensure exam integrity',
    },
    {
      icon: <AccessTime />,
      title: 'Flexible Scheduling',
      description: 'Take assessments anytime, anywhere',
    },
    {
      icon: <EmojiEvents />,
      title: 'Skill Certification',
      description: 'Earn recognized certificates for your achievements',
    },
    {
      icon: <School />,
      title: 'Learning Paths',
      description: 'Personalized recommendations for improvement',
    },
  ];

  const steps = [
    'Sign up for free',
    'Choose your assessment',
    'Take the AI-powered test',
    'Get instant results and feedback',
    'Track your progress',
  ];

  return (
    <Box>
      {/* Hero Section */}
      <Paper
        sx={{
          position: 'relative',
          backgroundColor: 'primary.main',
          color: 'white',
          py: 10,
          px: 3,
          textAlign: 'center',
          backgroundImage: 'linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7))',
        }}
      >
        <Container maxWidth="lg">
          <Typography variant="h2" gutterBottom fontWeight="bold">
            AI-Powered Skill Assessment Platform
          </Typography>
          <Typography variant="h5" gutterBottom sx={{ mb: 4, opacity: 0.9 }}>
            Assess, Improve, and Certify Your Skills with Advanced AI Technology
          </Typography>
          
          <Box sx={{ mt: 4 }}>
            <Button
              variant="contained"
              color="secondary"
              size="large"
              endIcon={<ArrowForward />}
              onClick={() => navigate('/register')}
              sx={{ mr: 2, py: 1.5, px: 4 }}
            >
              Get Started Free
            </Button>
            <Button
              variant="outlined"
              color="inherit"
              size="large"
              startIcon={<PlayCircle />}
              onClick={() => navigate('/login')}
              sx={{ py: 1.5, px: 4 }}
            >
              Take a Demo
            </Button>
          </Box>
        </Container>
      </Paper>

      {/* Features Section */}
      <Container maxWidth="lg" sx={{ py: 8 }}>
        <Typography variant="h3" align="center" gutterBottom>
          Why Choose Our Platform?
        </Typography>
        <Typography variant="h6" align="center" color="textSecondary" sx={{ mb: 6 }}>
          Experience the future of skill assessment
        </Typography>

        {/* container prop ብቻ ነው የሚጠቀመው */}
        <Grid container spacing={4}>
          {features.map((feature, index) => (
            /* size prop ነው የሚጠቀመው፤ item የሚለው አይፈለግም */
            <Grid size={{ xs: 12, sm: 6, md: 4 }} key={index}>
              <Card sx={{ height: '100%', transition: 'transform 0.2s', '&:hover': { transform: 'translateY(-4px)' } }}>
                <CardContent sx={{ textAlign: 'center', p: 4 }}>
                  <Box sx={{ color: 'primary.main', mb: 2, fontSize: 48 }}>
                    {feature.icon}
                  </Box>
                  <Typography variant="h6" gutterBottom>
                    {feature.title}
                  </Typography>
                  <Typography color="textSecondary">
                    {feature.description}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>

      {/* How It Works */}
      <Box sx={{ bgcolor: 'grey.50', py: 8 }}>
        <Container maxWidth="lg">
          <Typography variant="h3" align="center" gutterBottom>
            How It Works
          </Typography>
          
          <Grid container spacing={4} sx={{ mt: 4 }}>
            <Grid size={{ xs: 12, md: 6 }}>
              <Paper sx={{ p: 4, height: '100%' }}>
                <List>
                  {steps.map((step, index) => (
                    <React.Fragment key={index}>
                      <ListItem>
                        <ListItemIcon>
                          <CheckCircle color="primary" />
                        </ListItemIcon>
                        <ListItemText
                          primary={`Step ${index + 1}`}
                          secondary={step}
                          primaryTypographyProps={{ variant: 'h6' }}
                        />
                      </ListItem>
                      {index < steps.length - 1 && <Divider variant="inset" component="li" />}
                    </React.Fragment>
                  ))}
                </List>
              </Paper>
            </Grid>
            
            <Grid size={{ xs: 12, md: 6 }}>
              <Box sx={{ p: 3 }}>
                <Typography variant="h5" gutterBottom>
                  Trusted by Students and Professionals
                </Typography>
                <Typography paragraph>
                  Our platform uses state-of-the-art AI to provide accurate assessments 
                  that help you identify your strengths and weaknesses.
                </Typography>
                <Typography paragraph>
                  With our integrity monitoring system, you can be confident that 
                  your results are valid and recognized by employers.
                </Typography>
                
                <Box sx={{ mt: 4 }}>
                  <Grid container spacing={2}>
                    <Grid size={{ xs: 6 }}>
                      <Typography variant="h4" color="primary" align="center">
                        10,000+
                      </Typography>
                      <Typography align="center" color="textSecondary">
                        Assessments Taken
                      </Typography>
                    </Grid>
                    <Grid size={{ xs: 6 }}>
                      <Typography variant="h4" color="primary" align="center">
                        95%
                      </Typography>
                      <Typography align="center" color="textSecondary">
                        User Satisfaction
                      </Typography>
                    </Grid>
                  </Grid>
                </Box>
              </Box>
            </Grid>
          </Grid>
        </Container>
      </Box>

      {/* CTA Section */}
      <Container maxWidth="lg" sx={{ py: 8, textAlign: 'center' }}>
        <Typography variant="h3" gutterBottom>
          Ready to Start Your Journey?
        </Typography>
        <Typography variant="h6" color="textSecondary" gutterBottom sx={{ mb: 4 }}>
          Join thousands of successful candidates who have improved their skills with our platform
        </Typography>
        
        <Button
          variant="contained"
          color="primary"
          size="large"
          endIcon={<ArrowForward />}
          onClick={() => navigate('/register')}
          sx={{ py: 1.5, px: 6, fontSize: '1.1rem' }}
        >
          Create Free Account
        </Button>
        
        <Typography variant="body2" color="textSecondary" sx={{ mt: 2 }}>
          No credit card required • 14-day free trial • Cancel anytime
        </Typography>
      </Container>
    </Box>
  );
};

export default LandingPage;